apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: podconfig-operator
  name: cnf-test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podconfig-operator
  namespace: cnf-test
  labels:
    control-plane: podconfig-operator
spec:
  selector:
    matchLabels:
      control-plane: podconfig-operator
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: podconfig-operator
    spec:
      serviceAccountName: podconfig-operator-sa
      containers:
      - command:
        - /manager
        args:
        - --enable-leader-election
        image: controller:latest
        imagePullPolicy: Always
        name: podconfig-operator
        resources:
          limits:
            cpu: 100m
            memory: 300Mi
          requests:
            cpu: 100m
            memory: 200Mi
        securityContext:
          privileged: true
        volumeMounts:
          - mountPath: /tmp/proc
            name: proc
          - mountPath: /var/run/crio/crio.sock
            name: crio-sock
      volumes:
      - name: proc
        hostPath:
          # Mounting the proc file system to get process namespaces
          path: /proc
          type: Directory
      - name: crio-sock
        hostPath:
          # Mounting the proc file system to get process namespaces
          path: /var/run/crio/crio.sock
          type: Socket


      terminationGracePeriodSeconds: 10
