apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
  name: cnf-test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: cnf-test
  labels:
    control-plane: controller-manager
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      serviceAccountName: podconfig-operator-sa
      containers:
      - command:
        - /manager
        args:
        - --enable-leader-election
        image: controller:latest
        name: manager
        resources:
          limits:
            cpu: 100m
            memory: 300Mi
          requests:
            cpu: 100m
            memory: 200Mi
        securityContext:
          privileged: true
        volumeMounts:
          - mountPath: /proc
            name: proc
      volumes:
      - name: proc
        hostPath:
          # Mounting the proc file system to get process namespaces
          path: /proc
          type: Directory 
      terminationGracePeriodSeconds: 10
