# permissions for end users to edit trunkports.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: trunkport-editor-role
rules:
- apiGroups:
  - podconfig.opdev.io
  resources:
  - trunkports
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - podconfig.opdev.io
  resources:
  - trunkports/status
  verbs:
  - get
