apiVersion: podconfig.opdev.io/v1alpha1
kind: PodConfig
metadata:
  name: podconfig-sample-b
spec:
  # Add fields here
  sampleDeployment:
    create: false
    name: cnf-example-b
    
  networkAttachments:
    - name: pc0
      linkType: veth
      master: pcbr2
      parent: pc0
      cidr: "192.168.50.0/24"
    - name: pc1
      linkType: veth
      master: pcbr3
      parent: pc1
      cidr: "192.168.51.0/24"      